### ISSUE TITLE
Problem Running Code

### ISSUE THREAD

**Issue by stefano1989** [JesseVent/Crypto-Market-Scraper#1]
Hi, thanks for the wonderful work here.
I'm trying to run your code e on the console there are those errors
what am i doing wrong?:
![image](https://user-images.githubusercontent.com/9549124/32417655-dd7f557c-c25c-11e7-806e-d9033063baff.png)
![image](https://user-images.githubusercontent.com/9549124/32417661-f23f521e-c25c-11e7-8450-7e923a4a4148.png)

**Comment by JesseVent** [comment]
Hi Stefano, have you tried running the latest script? I did a huge refactor last night

**Comment by stefano1989** [comment]
I tried and now it run smooth untill the 100% now it gives me a timeout error and I don't know why

**Comment by JesseVent** [comment]
Its probably to do with the doSNOW package/using the progress bar line. 

just to be safe try adding these at the top
library(jsonlite)
library(plyr)
library(dplyr)
library(doSNOW)
library(doParallel)
library(lubridate)

**Comment by stefano1989** [comment]
![image](https://user-images.githubusercontent.com/9549124/32462625-5c7dea5e-c33a-11e7-8efb-d616808038b7.png)
![image](https://user-images.githubusercontent.com/9549124/32462646-6a581cbc-c33a-11e7-85de-74c51c9754ab.png)
![image](https://user-images.githubusercontent.com/9549124/32462663-75139f8c-c33a-11e7-9644-0450eea99ea2.png)


`require(jsonlite)
require(dplyr)
require(doSNOW)
require(lubridate)

# Functions ---------------------------------------------------------------
# Retrieve Coin Listings -----
getCoins <- function() {

	library(jsonlite)
	library(plyr)
	library(dplyr)
	library(doSNOW)
	library(doParallel)
	library(lubridate)
     today <- gsub("-", "", today())
     json <- "https://files.coinmarketcap.com/generated/search/quick_search.json"
     coins <- jsonlite::read_json(json, simplifyVector = TRUE)
     coins <- data_frame(symbol = coins$symbol, name = coins$name, slug = coins$slug,
          rank = coins$rank)
     length <- as.numeric(length(coins$slug))
     range <- 1:length
     url <- paste0("https://coinmarketcap.com/currencies/", coins$slug, "/historical-data/?start=20130428&end=",
          today)
     baseurl <- c(url)
     coins$slug <- as.character(baseurl)
     coins$rank <- as.numeric(coins$rank)
     return(coins)
}
# Scrape Historical Tables -----
abstracts <- function(attributes) {
     page <- read_html(attributes)
     names <- page %>% html_nodes(css = ".col-sm-4 .text-large") %>% html_text(trim = TRUE) %>%
          replace(!nzchar(.), NA)
     nodes <- page %>% html_nodes(css = "table") %>% .[1] %>% html_table(fill = TRUE) %>%
          replace(!nzchar(.), NA)
     abstracts <- Reduce(rbind, nodes)
     abstracts$symbol <- gsub("\\(||\\n|\\)|\\s\\s", "", names)
     abstracts$symbol <- as.character(strsplit(abstracts$symbol, " ")[[1]][1])
     return(abstracts)
}
# Cleanup results table -----
cleanUp <- function(results) {
     names(results) <- c("symbol", "name", "ranknow", "date", "open", "high", "low",
          "close", "volume", "market")
     marketdata <- results
     marketdata$volume <- gsub("\\,", "", marketdata$volume)
     marketdata$market <- gsub("\\,", "", marketdata$market)
     marketdata$volume <- gsub("\\-", "0", marketdata$volume)
     marketdata$market <- gsub("\\-", "0", marketdata$market)
     marketdata$close <- gsub("\\-", "0", marketdata$close)
     marketdata$date <- format(strptime(marketdata$date, format = "%b %d,%Y"), "%Y-%m-%d")
     marketdata$open <- as.numeric(marketdata$open)
     marketdata$close <- as.numeric(marketdata$close)
     marketdata$high <- as.numeric(marketdata$high)
     marketdata$low <- as.numeric(marketdata$low)
     marketdata$volume <- as.numeric(marketdata$volume)
     marketdata$market <- as.numeric(marketdata$market)
     # Percent variance between open and close rates
     marketdata$variance <- ((marketdata$close - marketdata$open)/marketdata$close)
     # spread variance between days high, low and closing
     marketdata$volatility <- ((marketdata$high - marketdata$low)/marketdata$close)
     return(marketdata)
}

# START CRYPTOCURRENCY SCRAPING SCRIPT ------------------------------------
# Crypto Scraping Setup ---------------------------------------------------
file <- "~\Desktop\Crypto-Markets.csv"
coins <- getCoins()
length <- as.numeric(length(coins$slug))
range <- 1:length
cpucore <- as.numeric(detectCores(all.tests = FALSE, logical = TRUE))
ptm <- proc.time()

# Parallel process scraping with progress bar -----------------------------
cluster = makeCluster(cpucore, type = "SOCK")
registerDoSNOW(cluster)
pb <- txtProgressBar(max = length, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
attributes <- coins$slug

# Combine results and stop clusters ---------------------------------------
results = foreach(i = range, .options.snow = opts, .combine = rbind, .packages = "rvest") %dopar%
     abstracts(attributes[i])
close(pb)
stopCluster(cluster)

# Cleanup results and fix names -------------------------------------------
coinnames <- data_frame(symbol = coins$symbol, name = coins$name, rank = coins$rank)
results <- merge(results, coinnames)
marketdata <- cleanUp(results)
write.csv(marketdata, file, row.names = FALSE)
`

**Comment by stefano1989** [comment]
same error. don't know why

**Comment by JesseVent** [comment]
I would say you are behind a proxy or some kind of network issue causing it to timeout. Google "rvest timeout proxy" and theres heaps on it. 
Only thing I could also recommend is try changing the read_html(attributes) call in the abstracts function to the below
 ```
library(curl)
page <- read_html(curl(attributes, handle = curl::new_handle("useragent" = "Mozilla/5.0")))
```

Don't think theres anything more I can do on my end.

**Comment by stefano1989** [comment]
Jesse Now works like a charme, thanks for helping.
For reference ive declared also library(rvest) in the abstract, for avoid the timeout.
