### ISSUE TITLE
Defining close_ratio

### ISSUE THREAD

**Issue by datGryphon** [JesseVent/Crypto-Market-Scraper#2]
Hi, I was hoping you could elaborate on what the close_ratio column represents. On kaggle you described it as "the daily close rate, min-maxed with the high and low values for the day." I do not know what min-maxed means in this context. Could you please explain?

**Comment by JesseVent** [comment]
Imagine you have a scale between the Lowest point for that day, and the highest point and want to know where it closed that day in comparison to high and low points.
The logic is as follows:
`CLOSE_RATE = (close - low) / (high - low)

Take example the following diagrams where CLOSE_RATE = X

`low= 1, high=2, close=1.5`

LOWEST &lt;----------------------------------------------------X----------------------------------------------------&gt; HIGHEST

**CLOSE_RATE IS EQUAL TO 0.50**

close_rate is the normalised (between 0 - 1) value to represent X in the above diagram and is worked out as follows.

      CLOSE_RATE = (1.5 - 1) / (2 - 1)
      CLOSE_RATE = (0.5) / (1)
      CLOSE_RATE = 0.5

----------

`low= 1, high=2, close=1.75`

LOWEST &lt;------------------------------------------------------------------------------X--------------------------&gt; HIGHEST

**CLOSE_RATE IS EQUAL TO  0.75**


----------


`low= 1, high=2, close=1.25`

LOWEST &lt;--------------------------X------------------------------------------------------------------------------&gt; HIGHEST

**CLOSE_RATE IS EQUAL TO 0.25**

**Comment by datGryphon** [comment]
Thanks so much. Stared your repository. If I ever find myself in the possession of some BTC I'll by you a coffee.
